### ISSUE TITLE
Naming Consistency in the AddOn List

### ISSUE THREAD

**Issue by Frurox** [N6REJ/Adibags_Bears_Alchemy#14]
This is not an issue, but more something that has to do with Naming Consistency and hope is a simple and fast fix.
These look good
<img width="317" alt="image" src="https://user-images.githubusercontent.com/47403751/202544307-b198883c-9b8e-4ae0-a464-b89c6ca7740b.png">
This one is missing the space before and after the -
<img width="244" alt="image" src="https://user-images.githubusercontent.com/47403751/202544544-6ca804ee-2ccd-4c5b-850e-36eb188e11a8.png">

**Comment by jwaisner** [comment]
Looks corrected now.

![image](https://user-images.githubusercontent.com/12568201/209728488-6810ac11-74af-434b-bf9d-892792703a71.png)
